
/*

10 난이도 계량 

*/


SELECT GRPNM,CID,CNAME,CRANK,SID,SNAME,SRANK,BID,BCID,BNAME,BRANK,PID,PNAME,PRANK,OID,ORANK,ONAME,MID,MCID,MEASUREID,MNAME,MRANK,  
        MEACHAR,MEA_TP,EVALTYPE,EVALTYPENM,TREND,EVAL_WEIGHT, 
        PLANNED,BASE,LIMIT,ACTUAL,SCORE,ROUND((NVL(SCORE,0)*NVL(EVAL_WEIGHT,0)/100),3) WGTSCR, 
        EVALRATE,EVALSCORE,ROUND((NVL(EVALSCORE,0)*NVL(EVAL_WEIGHT,0)/100),3) WGTEVALSCR     
 FROM  
 (  
          SELECT * FROM  
          (  
               SELECT G1.GRPNM, CID,CNAME,CRANK,SID,SNAME,SRANK,BID,BCID,V.BNAME,BRANK,PID,PNAME,PRANK,OID,ORANK,ONAME,MID,MCID,MEASUREID,MNAME,MRANK, 
                     MEACHAR,MEA_TP,EVALTYPE,FREQUENCY,TREND, EVAL_WEIGHT, (SELECT DIV_NM FROM TBGCOMMONCODE C WHERE C.LDIV_CD='E02' AND C.SDIV_CD=EVALTYPE) EVALTYPENM 
               FROM VIEW_MEASURE V, TBLEVALGRP01 G1, TBLEVALGRP02 G2 
               WHERE G1.YEAR=G2.YEAR AND G1.GRPCD=G2.GRPCD AND G1.YEAR=V.YEAR AND G2.BSCID=V.BCID 
                     AND V.YEAR=2015 AND V.MEASUREMENT='계량' 
          ) M 
          LEFT JOIN 
          ( 
             SELECT MEASUREID BSCMID, ACTUAL BSCACT FROM TBLMEASUREDETAIL WHERE STRDATE LIKE 2015||'12%' 
          ) DT 
          ON M.MCID=DT.BSCMID    
          LEFT JOIN  
          (  
              SELECT YEAR,MEASUREID EMID,PLANNED,BASE,LIMIT,ROUND(ACTUAL,3) ACTUAL,ROUND(BSCSCORE,3) SCORE, EVALRATE, EVALSCORE FROM TBEEVALSTANDARD WHERE YEAR=2015  
          ) EVL  
          ON M.MCID=EVL.EMID              
 )        WHERE  MID IS NOT NULL  
 ORDER BY CRANK,CID,SRANK,SID,BRANK,BID,PRANK,PID,ORANK,OID,MRANK,MID
 
 



/*

20 비계량 표준화   

*/





SELECT * FROM ( 
 SELECT GRPCD,GRPNM,YEAR,GSORT,BSCID,BNAME,DSORT,MCID,MNAME,AID,APPTYPE,APPNAME,EVALSCORE,AVG_APP,STD_APP,AVG_TOT,STD_TOT, 
        INSTD,CALSCR,  
        CASE WHEN STD_TOT>INSTD*3 THEN 1 ELSE 0 END TAG, 
        ROUND( 
        CASE WHEN APPTYPE=1 THEN 
            CASE WHEN (COUNT(CALSCR) OVER (PARTITION BY MCID,APPTYPE)>3) THEN 
            (SUM(CALSCR) OVER (PARTITION BY MCID,APPTYPE) - MAX(CALSCR) OVER (PARTITION BY MCID,APPTYPE) - MIN(CALSCR) OVER (PARTITION BY MCID,APPTYPE) ) 
            /(COUNT(CALSCR) OVER (PARTITION BY MCID,APPTYPE) - 2)  
            ELSE AVG(CALSCR) OVER (PARTITION BY MCID,APPTYPE) END 
        WHEN APPTYPE=2 THEN 
            AVG(CALSCR) OVER (PARTITION BY MCID,APPTYPE) 
        END 
        ,3) MAVR 
 FROM (        
 SELECT GRPCD,GRPNM,YEAR,GSORT,BSCID,BNAME,DSORT,MCID,MNAME,AID,APPTYPE,APPNAME,EVALSCORE,AVG_APP,STD_APP,AVG_TOT,STD_TOT, 
             INSTD, 
             CASE WHEN APPTYPE=1 THEN 
                  AVG_TOT+(EVALSCORE-AVG_APP)/STD_APP*STD_TOT 
             WHEN APPTYPE=2 THEN  
                  CASE WHEN STD_TOT>INSTD*3 THEN 
                     AVG_TOT+(EVALSCORE-AVG_APP)/STD_APP*(INSTD*3) 
                  ELSE 
                     AVG_TOT+(EVALSCORE-AVG_APP)/STD_APP*STD_TOT 
                  END 
             END CALSCR FROM 
             ( 
             SELECT GRPCD,GRPNM,YEAR,GSORT,BSCID,BNAME,DSORT,BID,BCID,MID,MCID,MNAME,GRPID,AID,APPTYPE,APPNAME,EVALSCORE, 
                    AVG(EVALSCORE) OVER (PARTITION BY GRPCD,APPTYPE,AID) AVG_APP, 
                    STDDEV(EVALSCORE) OVER (PARTITION BY GRPCD,APPTYPE,AID) STD_APP, 
                    AVG(EVALSCORE) OVER (PARTITION BY GRPCD, APPTYPE) AVG_TOT, 
                    STDDEV(EVALSCORE) OVER (PARTITION BY GRPCD, APPTYPE) STD_TOT, 
                    STDDEV( (DECODE(APPTYPE,1,EVALSCORE,NULL))) OVER (PARTITION BY GRPCD) INSTD       
             FROM (     
                     SELECT * FROM  
                     ( 
                         SELECT G1.GRPCD,GRPNM,G1.YEAR,G1.SORTBY GSORT,G2.BSCID,G2.BNAME, G2.SORTBY DSORT 
                         FROM TBLEVALGRP01 G1, TBLEVALGRP02 G2 
                         WHERE G1.YEAR=2014 AND G1.GRPCD=G2.GRPCD AND G1.YEAR=G2.YEAR 
                     ) G 
                     LEFT JOIN 
                     ( 
                         SELECT BID,BCID,MID,MCID,MNAME FROM VIEW_MEASURE WHERE YEAR=2015 AND MEASUREMENT='비계량' 
                     ) M 
                     ON G.BSCID=M.BCID 
                     LEFT JOIN 
                     ( 
                         SELECT D.GRPID,D.APPID AID,(SELECT USERNAME FROM TBLUSER U WHERE U.USERID=D.APPID) APPNAME,R.APPTYPE 
                         FROM TBQEVALDEPT D, TBQEVALER R WHERE D.APPID=R.APPID AND D.YEAR=R.YEAR AND D.MONTH=R.MONTH AND D.YEAR=2015 AND D.MONTH=12 
                     ) Q 
                     ON G.GRPCD=Q.GRPID 
                     LEFT JOIN 
                     (  
                         SELECT APPID,MEASUREID,EVALSCORE FROM TBQEVALDETAIL WHERE YEAR=2015 AND MONTH=12 
                     ) D 
                     ON M.MCID=D.MEASUREID AND Q.AID=D.APPID    
                 ) WHERE MCID IS NOT NULL  
             ) 
         ORDER BY AID,GSORT,DSORT,AID,MCID 
 ) 
 )    
 ORDER BY GSORT,DSORT,MCID,AID





 -- 비계량 평가자 정보
select appname||'('||appid||')'
from  
(
SELECT (SELECT USERNAME FROM TBLUSER U WHERE U.USERID=APPID) APPNAME,APPID, APPTYPE 
FROM TBQEVALER WHERE YEAR=2014
ORDER BY APPTYPE, APPID
)



SELECT * FROM
(
    SELECT * FROM
    (
        SELECT CID,CRANK,SID,SRANK,BID,BRANK,BCID,
               PID,PRANK, OID,ORANK,MRANK,MID,MCID,MNAME FROM VIEW_MEASURE WHERE YEAR=2015 AND MEASUREMENT='비계량' 
    ) A,
    (
    SELECT R.APPID,(SELECT USERNAME FROM TBLUSER U WHERE U.USERID=R.APPID) APPNAME, R.APPTYPE
    FROM TBQEVALER R WHERE R.YEAR=2014 
    ) B
) A
LEFT JOIN
(
    SELECT APPID AID,MEASUREID,EVALSCORE FROM TBQEVALDETAIL WHERE YEAR=2015 AND MONTH=12 
) B
ON A.APPID=B.AID AND A.MCID=B.MEASUREID
ORDER BY APPTYPE, APPID, CRANK,CID, SRANK,SID, BRANK,BID,PRANK,PID,ORANK,OID,MRANK,MID 







-----------------  비계량 원점수 추출 


SELECT * FROM  
( 
   SELECT G1.GRPCD,GRPNM,G1.YEAR,G1.SORTBY GSORT,G2.BSCID,G2.BNAME, G2.SORTBY DSORT 
   FROM TBLEVALGRP01 G1, TBLEVALGRP02 G2 
   WHERE G1.YEAR=2015 AND G1.GRPCD=G2.GRPCD AND G1.YEAR=G2.YEAR 
) G 
LEFT JOIN 
( 
 SELECT BID,BCID,MID,MCID,MNAME,EVAL_WEIGHT, func_getEvalScr(year,mcid) evalscore FROM VIEW_MEASURE WHERE YEAR=2015 AND MEASUREMENT='비계량' 
) M 
ON G.BSCID=M.BCID 
 ORDER BY GSORT,DSORT,MCID


SELECT * FROM VIEW_MEASURE


SELECT * FROM 
( 
   SELECT G1.GRPCD,GRPNM,G1.YEAR,G1.SORTBY GSORT,G2.BSCID,G2.BNAME, G2.SORTBY DSORT 
   FROM TBLEVALGRP01 G1, TBLEVALGRP02 G2 
   WHERE G1.YEAR=2015 AND G1.GRPCD=G2.GRPCD AND G1.YEAR=G2.YEAR 
) G
LEFT JOIN 
( 
   SELECT SNAME,BCID,BNAME,MNAME,MCID
   FROM VIEW_MEASURE M
   WHERE M.YEAR=2015 AND MEASUREMENT='비계량'
) V
ON G.BSCID= V.BCID
LEFT JOIN 
( 
 SELECT MEASUREID, INSCR,OUTSCR,INRT,OUTRT,EVALSCR FROM TBQEVALSTANDARD WHERE YEAR=2015 
) M 
ON V.MCID=M.MEASUREID
 ORDER BY GSORT,DSORT,MCID 


SELECT * FROM TBQEVALSTANDARD



/*
  3. 비계량 경평 
*/

SELECT * FROM 
 ( 
     SELECT YEAR,SECTIONID,(SELECT DIV_NM FROM TBGCOMMONCODE WHERE LDIV_CD='G01' AND SDIV_CD=SECTIONID) SNAME, 
            ENAME,MEAID,NAME,MEASUREMENT,WEIGHT,SORTBY FROM TBGMEASURE WHERE YEAR=2015 AND MEASUREMENT='비계량' 
 ) GM 
 LEFT JOIN 
 ( 
     SELECT MEAID AMID,OURSCORE, FINALATTAIN FROM TBGMEASURESTD WHERE YEAR=2015 
 ) GA 
 ON GM.MEAID=GA.AMID 
 LEFT JOIN 
 ( 
     SELECT GOVMID,BSCMID,BNAME,MEASUREID,(SELECT NAME FROM TBLMEASURE M WHERE M.ID=MEASUREID) MNAME FROM TBGBSCMEASURE WHERE YEAR=2015 
 ) MA 
 ON GM.MEAID=MA.GOVMID 
 LEFT JOIN 
 ( 
     SELECT MEASUREID EMID,ROUND(EVALSCR,3) EVALSCR,ROUND(MANGSCR,3) MANGSCR,EVALRT,MANGRT,ROUND(FINSCR,3) FINSCR FROM TBQEVALSTANDARD WHERE YEAR=2015 AND MONTH=12 
 ) MS 
 ON MA.BSCMID = MS.EMID      
 LEFT JOIN 
 ( 
     SELECT MEASUREID ACTMID,ROUND(ACTUAL,3) ACTUAL,PLANNED,BASE,LIMIT FROM TBLMEASUREDETAIL WHERE STRDATE LIKE 201512||'%' 
 ) DT 
 ON MA.BSCMID=DT.ACTMID   
 ORDER BY SECTIONID,SORTBY,MEAID,BSCMID
 
 
 
 
 
 
 
 
 
 
 /*
  4. 지표변 표준화 
 */
 
 SELECT  
   YEAR, GRPCD,GRPNM, GSORT, DSORT,BID,BNAME,BRANK,PID,PNAME,PRANK, 
   OID,ONAME,ORANK,MID,MCID,MNAME,MRANK,EVAL_WEIGHT,FREQUENCY,TREND, 
   EVALTYPE, EVALTYPENM, 
   MEASUREMENT,MEACHAR,MEA_TP, 
   EMID,RAWSCR,GAVG,GSTD,MAVG,MSTD,STDSCR, (STDSCR*NVL(EVAL_WEIGHT,0)/100) WGTSCR 
 FROM 
 ( 
     SELECT G1.YEAR, G1.GRPCD,G1.GRPNM,G1.SORTBY GSORT,G2.SORTBY DSORT,BID,M.BNAME,BRANK,PID,PNAME,PRANK, 
            OID,ONAME,ORANK,MID,MCID,MNAME,MRANK,EVAL_WEIGHT,FREQUENCY,TREND, 
            EVALTYPE,(SELECT DIV_NM FROM TBGCOMMONCODE C WHERE C.LDIV_CD='E02' AND C.SDIV_CD=EVALTYPE) EVALTYPENM, 
            MEASUREMENT,MEACHAR,MEA_TP  
     FROM TBLEVALGRP01 G1, TBLEVALGRP02 G2, VIEW_MEASURE M  
     WHERE G1.YEAR=2015 AND G1.YEAR=G2.YEAR AND G1.YEAR=M.YEAR 
           AND G1.GRPCD=G2.GRPCD AND G2.BSCID=M.BCID  
 ) M 
 LEFT JOIN 
 ( 
     SELECT MEASUREID EMID,RAWSCR,GAVG,GSTD,MAVG,MSTD,STDSCR FROM TBEMEASUREEVAL WHERE YEAR=2015  
 ) E 
 ON M.MCID=E.EMID 
 ORDER BY GSORT,DSORT,PRANK,PID,ORANK,OID,MRANK,MID




















