/**
 * 
 */
var smart_style = {
		"grid": {
            "paddingTop": "2",
            "paddingRight": "2",
            "paddingBottom": "2",
            "paddingLeft": "2",
            "iconAlignment": "center",
            "iconIndex": "0",
            "iconOffset": "0",
            "iconLocation": "left",
            "iconPadding": "0",
            "contentFit": "auto",
            "foreground": "#ff712f00",
            "hoveredMaskBackground": "#1f5292f7",
            "selectedForeground": "#ffffffff",
            "disabledForeground": "#ff808080",
            "hoveredBackground": "#1f5292f7",
            "textAlignment": "center",
            "lineAlignment": "center",
            "figureBackground": "#ff008800",
            "figureInactiveBackground": "#ffd3d3d3",
            "selectedBackground": "#ff696969",
            "background": "#ffffffff",
            "inactiveBackground": "#ffd3d3d3",
            "font": "맑은 고딕,12",
			/*그리드 테두리 속성*/
            "border": "#FFb6b6b6,1",
	        }, 
		/* 행의 속성  */
        "body": {
			/*홀수행의 속성*/
			dynamicStyles:[
				{criteria:"(row mod 2) = 0",
				styles:{
					background:"#FFF1F1F1"
					}
				}
			],
			/*짝수행의 속성*/
            "background": "#FFFFFFFF",
			/*행의 테두리 속성*/
            "borderRight": "#FFDEDEDE,1",
            "borderBottom": "#FFDEDEDE,1",
			/*행의 안쪽 간격 속성*/
            "paddingTop": "4",
            "paddingRight": "2",
            "paddingBottom": "4",
            "paddingLeft": "2",
			/*행의 글자 색*/
            "foreground": "#FF330000",
            "iconAlignment": "center",
            "iconIndex": "0",
            "iconOffset": "0",
            "iconLocation": "left",
            "iconPadding": "0",
            "contentFit": "auto",
            "hoveredMaskBackground": "#1f5292f7",
            "selectedForeground": "#ffffffff",
            "disabledForeground": "#ff808080",
            "hoveredBackground": "#1f5292f7",
            "textAlignment": "center",
            "lineAlignment": "center",
			
            /*상위메뉴 아이콘 tree Icon */
            "figureBackground": "#ff808080",
            "figureInactiveBackground": "#ffd3d3d3",
			/*tree line */            
			"line": "#ff808080,1",
            
            "selectedBackground": "#ff000000",
            "inactiveBackground": "#ffd3d3d3",
            "font": "돋움, 13",
            "border": "#ffb5b6b6,1",
            "empty": {
                "borderBottom": "#ff999999,1",
                "borderRight": "#ff999999,1",
                "paddingRight": "2",
                "paddingBottom": "2",
                "paddingLeft": "2",
                "iconAlignment": "center",
                "iconIndex": "0",
                "iconOffset": "0",
                "iconLocation": "left",
                "iconPadding": "0",
                "contentFit": "auto",
                "foreground": "#ff000000",
                "hoveredMaskBackground": "#1f5292f7",
                "selectedForeground": "#ffffffff",
                "disabledForeground": "#ff808080",
                "hoveredBackground": "#1f5292f7",
                "textAlignment": "center",
                "lineAlignment": "center",
                "figureBackground": "#ff008800",
                "figureInactiveBackground": "#ffd3d3d3",
                "selectedBackground": "#ff696969",
                "background": "#ffffffff",
                "inactiveBackground": "#ffd3d3d3",
                "font": "맑은 고딕,12",
                "border": "#ff313539,1",
            }
        },
		/* 컬럼속성 */
        "header": {
			/* 컬럼의 테두리 속성 */
            "borderTop":    "#ffCDCCCC,0",
            "borderRight":  "#ffCDCCCC,1",
            "borderBottom": "#ffCDCCCC,1",
            "borderLeft":   "#ffE4E4E4,0",		
			/* 컬럼의 안쪽 간격 속성 */
            "paddingTop":    "3",
            "paddingRight":  "2",
            "paddingBottom": "3",
            "paddingLeft":   "2",
			/* 컬럼의 배경 및 글자 속성 */
            "background": "linear, #FFF2F2F2,#FFDFDFDF, 90",
            "foreground": "#FF000000",
            "font": "맑은 고딕,14",
			/* hover된 컬럼의 배경 및 글자 속성 */
            "hoveredBackground": "linear, #FFE8E8E8,#FFE2E2E2, 90",
            "hoveredForeground": "#ff393939",
            "textAlignment": "center",
            "iconAlignment": "center",
            "iconIndex": "0",
            "iconOffset": "0",
            "iconLocation": "left",
            "iconPadding": "0",
            "contentFit": "auto",
			/* 정렬안되는 컬럼 배경 */
            "hoveredMaskBackground": "linear,#fffff8a9,#ffffd75e,90",
            "selectedForeground": "#ff2B2B2B",
            "disabledForeground": "#ff808080",
            "lineAlignment": "center",
            "figureBackground": "#ff000000",
            "figureInactiveBackground": "#ffd3d3d3",
			/*셀 선택시 컬럼 배경 속성   key */
            "selectedBackground": "linear, #FFFFFFFF,#FFEEEEEE, 90",
            "inactiveBackground": "#ffd3d3d3",
            "border": "#ffFF001A,1",
			/*그룹 컬럼 속성*/
            "group": {
				/* 그룹 컬럼의 테두리 속성 */
	            "borderTop": "#ffCDCCCC,0",
	            "borderRight": "#ffCDCCCC,1",
	            "borderBottom": "#ffCDCCCC,1",
	            "borderLeft": "#ffE4E4E4,1",		
				/* 그룹 컬럼의 안쪽 간격 속성 */
    	        "paddingTop": "3",
        	    "paddingRight": "2",
            	"paddingBottom": "3",
            	"paddingLeft": "2",
				/* 컬럼의 배경 색 및 글자 속성 */
            	"background": "linear, #FFF2F2F2,#FFe8e8e8, 90",
            	"foreground": "#ff000000",
            	"font": "맑은 고딕,14,",
				/* hover된 컬럼의 배경 및 글자 속성 */
	            "hoveredBackground":  "linear, #FFE8E8E8,#FFE2E2E2, 90",
            	"hoveredForeground": "#ff393939",
                "iconAlignment": "center",
                "iconIndex": "0",
                "iconOffset": "0",
                "iconLocation": "left",
                "iconPadding": "0",
                "contentFit": "auto",
                "hoveredMaskBackground": "linear,#fffff8a9,#ffffd75e,90",
                "selectedForeground": "#ffffffff",
                "disabledForeground": "#ff808080",
                "textAlignment": "center",
                "lineAlignment": "center",
                "figureBackground": "#ff008800",
                "figureInactiveBackground": "#ffd3d3d3",
                "selectedBackground": "#ff696969",
                "inactiveBackground": "#ffd3d3d3",
                "border": "#ff313539,1",
            }
        },
		
		/*숫자 열 (첫열)*/
        "indicator": {
			/*숫자열 테두리 속성*/
            "borderTop": "#ffE4E4E4,1",
            "borderRight": "#ffCDCCCC,1",
            "borderBottom": "#ffCDCCCC,1",
            "borderLeft": "#ffE4E4E4,1",
			/*숫자열 안쪽 간격*/
            "paddingTop": "2",
			"paddingRight": "2",
            "paddingBottom": "2",
            "paddingLeft": "2",
			/*숫자열 배경 및 글자 속성*/
            "background": "#ffE4E4E4",
            "foreground": "#ff393939",
            "font": "돋움,11",
			/*호버시 배경 및 글자 속성*/
            "hoveredBackground": "#5f666666",
            "hoveredForeground": "#ff393939",
			/*셀을 선택시 배경 및 글자 속성*/
            "selectedBackground": "#331F9CE0",
            "figureBackground": "#ff5E5E5E",
            "iconAlignment": "center",
            "iconIndex": "0",
            "iconOffset": "0",
            "iconLocation": "left",
            "iconPadding": "0",
            "contentFit": "auto",
            "textAlignment": "center",
            "lineAlignment": "center",
            "hoveredMaskBackground": "#fffff0b2",
            "selectedForeground": "#ffffffff",
            "disabledForeground": "#ff808080",
            "figureInactiveBackground": "#ffd3d3d3",
            "inactiveBackground": "#ffd3d3d3",
            "border": "#ffFF0000,1",
            "head": {
				/*숫자열 안쪽 테두리속성*/
	            "borderTop": "#ffCDCCCC,0",
    	        "borderRight": "#ffCDCCCC,1",
	            "borderBottom": "#ffCDCCCC,1",
            	"borderLeft": "#ffE4E4E4,1",
				/*숫자열 안쪽 간격*/
     	       	"paddingTop": "2",
				"paddingRight": "2",
            	"paddingBottom": "2",
    	        "paddingLeft": "2",
				/*숫자열 배경 및 글자 속성*/
            	"background": "linear, #FFF2F2F2,#FFDFDFDF, 90",
	       	    "foreground": "#ff393939",
            	"font": "돋움,11",
				/*호버시 배경 및 글자 속성*/
            	"hoveredBackground": "#ffBEAED4",
            	"hoveredForeground": "#ff402B5F",
				/*셀을 선택시 배경 및 글자 속성*/
            	"figureBackground": "#ff5E5E5E",
            	"selectedBackground": "#ffC0D2E2",
           	 	"iconAlignment": "center",
            	"iconIndex": "0",
            	"iconOffset": "0",
            	"iconLocation": "left",
            	"iconPadding": "0",
            	"contentFit": "auto",
            	"textAlignment": "center",
            	"lineAlignment": "center",
            	"hoveredMaskBackground": "#fffff0b2",
            	"selectedForeground": "#ffffffff",
            	"disabledForeground": "#ff808080",
            	"figureInactiveBackground": "#ffd3d3d3",
            	"inactiveBackground": "#ffd3d3d3",
            	"border": "#ffFF0000,1",
            },
            "foot": {
                "borderTop": "#ff79828b,1",
                "borderRight": "#ff9099a3,1",
                "borderBottom": "#ff808080,1",
                "borderLeft": "#ffffffff,1",
                "paddingTop": "2",
                "paddingRight": "2",
                "paddingBottom": "2",
                "paddingLeft": "2",
                "iconAlignment": "center",
                "iconIndex": "0",
                "iconOffset": "0",
                "iconLocation": "left",
                "iconPadding": "0",
                "contentFit": "auto",
                "foreground": "#ff000000",
                "hoveredMaskBackground": "#1f5292f7",
                "selectedForeground": "#ffffffff",
                "disabledForeground": "#ff808080",
                "hoveredBackground": "#1f5292f7",
                "textAlignment": "center",
                "lineAlignment": "center",
                "figureBackground": "#ff002f6e",
                "figureInactiveBackground": "#ffd3d3d3",
                "selectedBackground": "#ff696969",
                "background": "#ffdee2e7",
                "inactiveBackground": "#ffd3d3d3",
                "font": "맑은 고딕,12",
                "border": "#88888888,1",
            }
        },
		/*체크박스가 있는 열*/
        "checkBar": {
			/*체크박스 배경 색*/
            "background": "#ffffffff",
			/*체크박스 체크 색*/
            "figureBackground": "#ff5f5f5f",
			/*체크박스 테두리속성*/
            "borderRight": "#ffCDCCCC,1",
            "borderBottom": "#ffCDCCCC,1",
			/*체크박스 간격 속성*/
            "paddingTop": "2",
            "paddingRight": "2",
            "paddingBottom": "2",
            "paddingLeft": "2",
            "iconAlignment": "center",
            "iconIndex": "0",
            "iconOffset": "0",
            "iconLocation": "left",
            "iconPadding": "0",
            "contentFit": "auto",
            "foreground": "#ff555555",
            "hoveredMaskBackground": "#1f5292f7",
            "selectedForeground": "#ffffffff",
            "disabledForeground": "#ff808080",
            "hoveredBackground": "#1f5292f7",
            "textAlignment": "center",
            "lineAlignment": "center",
            "figureInactiveBackground": "#ffd3d3d3",
            "selectedBackground": "#ff696969",
            "inactiveBackground": "#ffd3d3d3",
            "font": "맑은 고딕,12",
            "border": "#ff313539,1",
            "head": {
				/*체크박스 배경색*/
	            "background": "linear, #FFF2F2F2,#FFDFDFDF, 90",
                /*체크박스 체크 색*/
            	"figureBackground": "#ff121212",
				/*체크박스열 테두리 속성*/
          	  	"borderTop": "#ffCDCCCC,0",
          	  	"borderRight": "#ffCDCCCC,1",
          	  	"borderBottom": "#ffCDCCCC,1",
          	  	"borderLeft": "#ffE4E4E4,1",
				/*체크박스 간격 속성*/
                "paddingTop": "2",
                "paddingRight": "2",
                "paddingBottom": "2",
                "paddingLeft": "2",
                "iconAlignment": "center",
                "iconIndex": "0",
                "iconOffset": "0",
                "iconLocation": "left",
                "iconPadding": "0",
                "contentFit": "auto",
                "foreground": "#ff000000",
                "hoveredMaskBackground": "#1f5292f7",
                "selectedForeground": "#ffffffff",
                "disabledForeground": "#ff808080",
                "hoveredBackground": "#1f5292f7",
                "textAlignment": "center",
                "hoveredForeground": "#ffffffff",
                "lineAlignment": "center",
                "figureInactiveBackground": "#ffd3d3d3",
                "selectedBackground": "#ff696969",
                "inactiveBackground": "#ffd3d3d3",
                "font": "맑은 고딕,12",
                "border": "#ff000000,0",
            },
            "foot": {
                "borderTop": "#ff79828b,1",
                "borderRight": "#ff9099a3,1",
                "borderBottom": "#ff808080,1",
                "borderLeft": "#ffffffff,1",
                "paddingTop": "2",
                "paddingRight": "2",
                "paddingBottom": "2",
                "paddingLeft": "2",
                "iconAlignment": "center",
                "iconIndex": "0",
                "iconOffset": "0",
                "iconLocation": "left",
                "iconPadding": "0",
                "contentFit": "auto",
                "foreground": "#ff000000",
                "hoveredMaskBackground": "#1f5292f7",
                "selectedForeground": "#ffffffff",
                "disabledForeground": "#ff808080",
                "hoveredBackground": "#1f5292f7",
                "textAlignment": "center",
                "lineAlignment": "center",
                "figureBackground": "#ff008800",
                "figureInactiveBackground": "#ffd3d3d3",
                "selectedBackground": "#ff696969",
                "background": "#ffdee2e7",
                "inactiveBackground": "#ffd3d3d3",
                "font": "맑은 고딕,12",
                "border": "#88888888,1",
            }
        },
		/*상태 바*/	
        "stateBar": {
            "borderRight": "#ffCDCCCC,1",
            "borderBottom": "#ffCDCCCC,1",
            "paddingTop": "2",
            "paddingRight": "2",
            "paddingBottom": "2",
            "paddingLeft": "2",
            "iconAlignment": "center",
            "iconIndex": "0",
            "iconOffset": "0",
            "iconLocation": "left",
            "iconPadding": "0",
            "contentFit": "auto",
            "foreground": "#ff000000",
            "hoveredMaskBackground": "#1f5292f7",
            "selectedForeground": "#ffffffff",
            "disabledForeground": "#ff808080",
            "hoveredBackground": "#1f5292f7",
            "textAlignment": "center",
            "lineAlignment": "center",
            "figureBackground": "#ff008800",
            "figureInactiveBackground": "#ffd3d3d3",
            "selectedBackground": "#ff696969",
            "background": "#ffffffff",
            "inactiveBackground": "#ffd3d3d3",
            "font": "맑은 고딕,12",
            "border": "#ff313539,1",
            "head": {
				/*상태 배경색*/
	            "background": "#ffE4E4E4",
                /*상태 체크 색*/
            	"figureBackground": "#ff008EDC",
				/*상태 테두리 속성*/
          	  	"borderTop": "#ffCDCCCC,0",
          	  	"borderRight": "#ffCDCCCC,1",
          	  	"borderBottom": "#ffCDCCCC,1",
          	  	"borderLeft": "#ffE4E4E4,1",
				/*상태 간격 속성*/
                "paddingTop": "2",
                "paddingRight": "2",
                "paddingBottom": "2",
                "paddingLeft": "2",
                "iconAlignment": "center",
                "iconIndex": "0",
                "iconOffset": "0",
                "iconLocation": "left",
                "iconPadding": "0",
                "contentFit": "auto",
                "foreground": "#ff000000",
                "hoveredMaskBackground": "#1f5292f7",
                "selectedForeground": "#ffffffff",
                "disabledForeground": "#ff808080",
                "hoveredBackground": "#1f5292f7",
                "textAlignment": "center",
                "hoveredForeground": "#ffffffff",
                "lineAlignment": "center",
                "figureBackground": "#ff008800",
                "figureInactiveBackground": "#ffd3d3d3",
                "selectedBackground": "#ff696969",
                "inactiveBackground": "#ffd3d3d3",
                "font": "맑은 고딕,12",
                "border": "#ff000000,0",
            },
            "foot": {
                "borderTop": "#ff79828b,1",
                "borderRight": "#ff9099a3,1",
                "borderBottom": "#ff808080,1",
                "borderLeft": "#ffffffff,1",
                "paddingTop": "2",
                "paddingRight": "2",
                "paddingBottom": "2",
                "paddingLeft": "2",
                "iconAlignment": "center",
                "iconIndex": "0",
                "iconOffset": "0",
                "iconLocation": "left",
                "iconPadding": "0",
                "contentFit": "auto",
                "foreground": "#ff000000",
                "hoveredMaskBackground": "#1f5292f7",
                "selectedForeground": "#ffffffff",
                "disabledForeground": "#ff808080",
                "hoveredBackground": "#1f5292f7",
                "textAlignment": "center",
                "lineAlignment": "center",
                "figureBackground": "#ff008800",
                "figureInactiveBackground": "#ffd3d3d3",
                "selectedBackground": "#ff696969",
                "background": "#ffdee2e7",
                "inactiveBackground": "#ffd3d3d3",
                "font": "맑은 고딕,12",
                "border": "#88888888,1",
            }
        },
        "selection": {
            "paddingTop": "0",
            "paddingRight": "0",
            "paddingBottom": "0",
            "paddingLeft": "0",
            "iconAlignment": "center",
            "iconIndex": "0",
            "iconOffset": "0",
            "iconLocation": "left",
            "iconPadding": "0",
            "contentFit": "auto",
            "foreground": "#ff000000",
            "hoveredMaskBackground": "#1f5292f7",
            
            "disabledForeground": "#ff808080",
            "hoveredBackground": "#1f5292f7",
            "textAlignment": "center",
            "lineAlignment": "center",
            "figureBackground": "#ff008800",
            "figureInactiveBackground": "#ffd3d3d3",

/* changed*/
			"selectedForeground": "#ffffffff",            
			"selectedBackground": "#ff6498aa",
			
/*  selected row color */
            "background": "#00ffffff",
            "inactiveBackground": "#FFd3d3d3",
            "font": ",13",
            "border": "#FF6599ea,2",
        }
    };


var realGridStyle = {
		"grid": {
			            "paddingTop": "2",
			            "paddingRight": "2",
			            "paddingBottom": "2",
			            "paddingLeft": "2",
			            "iconAlignment": "center",
			            "iconIndex": "0",
			            "iconOffset": "0",
			            "iconLocation": "left",
			            "iconPadding": "0",
			            "contentFit": "auto",
			            "foreground": "#ff712f00",
			            "hoveredMaskBackground": "#1f5292f7",
			            "selectedForeground": "#ffffffff",
			            "disabledForeground": "#ff808080",
			            "hoveredBackground": "#1f5292f7",
			            "textAlignment": "center",
			            "lineAlignment": "center",
			            "figureBackground": "#ff008800",
			            "figureInactiveBackground": "#ffd3d3d3",
			            "selectedBackground": "#ff696969",
			            "background": "#ffffffff",
			            "inactiveBackground": "#ffd3d3d3",
			            "font": "맑은 고딕,12",
						/*그리드 테두리 속성*/
			            "border": "#FFb6b6b6,1",
				        }, 
			        "panel": {
			            "borderRight": "#ff777777,1",
			            "borderBottom": "#ff688caf,1",
			            "paddingTop": "4",
			            "paddingRight": "2",
			            "paddingBottom": "5",
			            "paddingLeft": "8",
			            "iconAlignment": "center",
			            "iconIndex": "0",
			            "iconOffset": "0",
			            "iconLocation": "left",
			            "iconPadding": "0",
			            "contentFit": "auto",
			            "foreground": "#ff787878",
			            "hoveredMaskBackground": "#1f5292f7",
			            "selectedForeground": "#ffffffff",
			            "disabledForeground": "#ff808080",
			            "hoveredBackground": "#1f5292f7",
			            "textAlignment": "near",
			            "lineAlignment": "center",
			            "figureBackground": "#ff008800",
			            "figureInactiveBackground": "#ffd3d3d3",
			            "selectedBackground": "#ff696969",
			            "background": "#ffdee2e7",
			            "inactiveBackground": "#ffd3d3d3",
			            "font": "돋움,11",
			            "border": "#ff313539,1",
			        },
					/* 행의 속성  */
			        "body": {
						/*홀수행의 속성*/
						dynamicStyles:[
							{criteria:"(row mod 2) = 0",
		 					styles:{
		    					background:"#FFF1F1F1"
		 						}
							}
						],
						/*짝수행의 속성*/
			            "background": "#FFFFFFFF",
						/*행의 테두리 속성*/
			            "borderRight": "#FFDEDEDE,1",
			            "borderBottom": "#FFDEDEDE,1",
						/*행의 안쪽 간격 속성*/
			            "paddingTop": "6",
			            "paddingRight": "2",
			            "paddingBottom": "6",
			            "paddingLeft": "2",
						/*행의 글자 색*/
			            "foreground": "#FF330000",
			            "iconAlignment": "center",
			            "iconIndex": "0",
			            "iconOffset": "0",
			            "iconLocation": "left",
			            "iconPadding": "0",
			            "contentFit": "auto",
			            "hoveredMaskBackground": "#1f5292f7",
			            "selectedForeground": "#ffffffff",
			            "disabledForeground": "#ff808080",
			            "hoveredBackground": "#1f5292f7",
			            "textAlignment": "center",
			            "lineAlignment": "center",
						
			            /*상위메뉴 아이콘 tree Icon */
			            "figureBackground": "#ff808080",
			            "figureInactiveBackground": "#ffd3d3d3",
						/*tree line */            
						"line": "#ff808080,1",
			            
			            "selectedBackground": "#ff000000",
			            "inactiveBackground": "#ffd3d3d3",
			            "font": "돋움, 13",
			            "border": "#ffb5b6b6,1",
			            "empty": {
			                "borderBottom": "#ff999999,1",
			                "borderRight": "#ff999999,1",
			                "paddingRight": "2",
			                "paddingBottom": "2",
			                "paddingLeft": "2",
			                "iconAlignment": "center",
			                "iconIndex": "0",
			                "iconOffset": "0",
			                "iconLocation": "left",
			                "iconPadding": "0",
			                "contentFit": "auto",
			                "foreground": "#ff000000",
			                "hoveredMaskBackground": "#1f5292f7",
			                "selectedForeground": "#ffffffff",
			                "disabledForeground": "#ff808080",
			                "hoveredBackground": "#1f5292f7",
			                "textAlignment": "center",
			                "lineAlignment": "center",
			                "figureBackground": "#ff008800",
			                "figureInactiveBackground": "#ffd3d3d3",
			                "selectedBackground": "#ff696969",
			                "background": "#ffffffff",
			                "inactiveBackground": "#ffd3d3d3",
			                "font": "맑은 고딕,12",
			                "border": "#ff313539,1",
			            }
			        },
			        "fixed": {
			            "borderRight": "#ff999999,1",
			            "borderBottom": "#ff999999,1",
			            "paddingTop": "2",
			            "paddingRight": "2",
			            "paddingBottom": "2",
			            "paddingLeft": "2",
			            "iconAlignment": "center",
			            "iconIndex": "0",
			            "iconOffset": "0",
			            "iconLocation": "left",
			            "iconPadding": "0",
			            "contentFit": "auto",
			            "foreground": "#ff000000",
			            "hoveredMaskBackground": "#1f5292f7",
			            "selectedForeground": "#ffffffff",
			            "disabledForeground": "#ff808080",
			            "hoveredBackground": "#1f5292f7",
			            "textAlignment": "center",
			            "lineAlignment": "center",
			            "figureBackground": "#ff008800",
			            "figureInactiveBackground": "#ffd3d3d3",
			            "selectedBackground": "#ff696969",
			            "background": "#ffd3d3d3",
			            "inactiveBackground": "#ffd3d3d3",
			            "font": "맑은 고딕,12",
			            "border": "#88888888,1",
			            "colBar": {
			                "borderRight": "#ff808080,1",
			                "borderBottom": "#ff808080,1",
			                "paddingTop": "2",
			                "paddingRight": "2",
			                "paddingBottom": "2",
			                "paddingLeft": "2",
			                "iconAlignment": "center",
			                "iconIndex": "0",
			                "iconOffset": "0",
			                "iconLocation": "left",
			                "iconPadding": "0",
			                "contentFit": "auto",
			                "foreground": "#ff000000",
			                "hoveredMaskBackground": "#1f5292f7",
			                "selectedForeground": "#ffffffff",
			                "disabledForeground": "#ff808080",
			                "hoveredBackground": "#1f5292f7",
			                "textAlignment": "center",
			                "lineAlignment": "center",
			                "figureBackground": "#ff008800",
			                "figureInactiveBackground": "#ffd3d3d3",
			                "selectedBackground": "#ff696969",
			                "background": "#ffffffff",
			                "inactiveBackground": "#ffd3d3d3",
			                "font": "맑은 고딕,12",
			                "border": "#ff313539,1",
			            },
			            "rowBar": {
			                "borderRight": "#ff999999,1",
			                "borderBottom": "#ff999999,1",
			                "paddingTop": "2",
			                "paddingRight": "2",
			                "paddingBottom": "2",
			                "paddingLeft": "2",
			                "iconAlignment": "center",
			                "iconIndex": "0",
			                "iconOffset": "0",
			                "iconLocation": "left",
			                "iconPadding": "0",
			                "contentFit": "auto",
			                "foreground": "#ff000000",
			                "hoveredMaskBackground": "#1fFF0000",
			                "selectedForeground": "#ffffffff",
			                "disabledForeground": "#ff808080",
			                "hoveredBackground": "#1f5292f7",
			                "textAlignment": "center",
			                "lineAlignment": "center",
			                "figureBackground": "#ff008800",
			                "figureInactiveBackground": "#ffd3d3d3",
			                "selectedBackground": "#ff696969",
			                "background": "#ffd3d3d3",
			                "inactiveBackground": "#ffd3d3d3",
			                "font": "맑은 고딕,12",
			                "border": "#88888888,1",
			            }
			        },
					/* 컬럼속성 */
			        "header": {
						/* 컬럼의 테두리 속성 */
			            "borderTop":    "#ffCDCCCC,0",
			            "borderRight":  "#ffCDCCCC,1",
			            "borderBottom": "#ffCDCCCC,1",
			            "borderLeft":   "#ffE4E4E4,0",		
						/* 컬럼의 안쪽 간격 속성 */
			            "paddingTop":    "3",
			            "paddingRight":  "2",
			            "paddingBottom": "3",
			            "paddingLeft":   "2",
						/* 컬럼의 배경 및 글자 속성 */
			            "background": "linear, #FFF2F2F2,#FFDFDFDF, 90",
			            "foreground": "#FF000000",
			            "font": "맑은 고딕,14",
						/* hover된 컬럼의 배경 및 글자 속성 */
			            "hoveredBackground": "linear, #FFE8E8E8,#FFE2E2E2, 90",
			            "hoveredForeground": "#ff393939",
			            "textAlignment": "center",
			            "iconAlignment": "center",
			            "iconIndex": "0",
			            "iconOffset": "0",
			            "iconLocation": "left",
			            "iconPadding": "0",
			            "contentFit": "auto",
						/* 정렬안되는 컬럼 배경 */
			            "hoveredMaskBackground": "linear,#fffff8a9,#ffffd75e,90",
			            "selectedForeground": "#ff2B2B2B",
			            "disabledForeground": "#ff808080",
			            "lineAlignment": "center",
			            "figureBackground": "#ff000000",
			            "figureInactiveBackground": "#ffd3d3d3",
						/*셀 선택시 컬럼 배경 속성   key */
			            "selectedBackground": "linear, #FFFFFFFF,#FFEEEEEE, 90",
			            "inactiveBackground": "#ffd3d3d3",
			            "border": "#ffFF001A,1",
						/*그룹 컬럼 속성*/
			            "group": {
							/* 그룹 컬럼의 테두리 속성 */
				            "borderTop": "#ffCDCCCC,0",
				            "borderRight": "#ffCDCCCC,1",
				            "borderBottom": "#ffCDCCCC,1",
				            "borderLeft": "#ffE4E4E4,1",		
							/* 그룹 컬럼의 안쪽 간격 속성 */
			    	        "paddingTop": "3",
			        	    "paddingRight": "2",
			            	"paddingBottom": "3",
			            	"paddingLeft": "2",
							/* 컬럼의 배경 색 및 글자 속성 */
			            	"background": "linear, #FFF2F2F2,#FFe8e8e8, 90",
			            	"foreground": "#ff000000",
			            	"font": "맑은 고딕,14,",
							/* hover된 컬럼의 배경 및 글자 속성 */
				            "hoveredBackground":  "linear, #FFE8E8E8,#FFE2E2E2, 90",
			            	"hoveredForeground": "#ff393939",
			                "iconAlignment": "center",
			                "iconIndex": "0",
			                "iconOffset": "0",
			                "iconLocation": "left",
			                "iconPadding": "0",
			                "contentFit": "auto",
			                "hoveredMaskBackground": "linear,#fffff8a9,#ffffd75e,90",
			                "selectedForeground": "#ffffffff",
			                "disabledForeground": "#ff808080",
			                "textAlignment": "center",
			                "lineAlignment": "center",
			                "figureBackground": "#ff008800",
			                "figureInactiveBackground": "#ffd3d3d3",
			                "selectedBackground": "#ff696969",
			                "inactiveBackground": "#ffd3d3d3",
			                "border": "#ff313539,1",
			            }
			        },
					/* 하단에 있는 컬럼 */
			        "footer": {
			            "borderTop": "#ff79828b,1",
			            "borderRight": "#ff9099a3,1",
			            "paddingTop": "2",
			            "paddingRight": "2",
			            "paddingBottom": "1",
			            "paddingLeft": "2",
			            "iconAlignment": "center",
			            "iconIndex": "0",
			            "iconOffset": "0",
			            "iconLocation": "left",
			            "iconPadding": "0",
			            "contentFit": "auto",
			            "foreground": "#ff000000",
			            "hoveredMaskBackground": "#1f5292f7",
			            "selectedForeground": "#ffffffff",
			            "disabledForeground": "#ff808080",
			            "hoveredBackground": "#1f5292f7",
			            "textAlignment": "near",
			            "lineAlignment": "center",
			            "figureBackground": "#ff008800",
			            "figureInactiveBackground": "#ffd3d3d3",
			            "selectedBackground": "#ff696969",
			            "background": "#ffdee2e7",
			            "inactiveBackground": "#ffd3d3d3",
			            "font": "맑은 고딕,12",
			            "border": "#88888888,1",
			        },
			        "rowGroup": {
			            "header": {
			                "borderTop": "#ffffffff,0",
			                "borderRight": "#ff85a8d0,1",
			                "borderBottom": "#ff85a8d0,1",
			                "borderLeft": "#ffffffff,1",
			                "paddingTop": "2",
			                "paddingRight": "2",
			                "paddingBottom": "2",
			                "paddingLeft": "2",
			                "iconAlignment": "center",
			                "iconIndex": "0",
			                "iconOffset": "0",
			                "iconLocation": "left",
			                "iconPadding": "0",
			                "contentFit": "auto",
			                "foreground": "#ff002f6e",
			                "hoveredMaskBackground": "#1f5292f7",
			                "selectedForeground": "#ffffffff",
			                "disabledForeground": "#ff808080",
			                "hoveredBackground": "#1f5292f7",
			                "textAlignment": "near",
			                "lineAlignment": "center",
			                "figureBackground": "#ff008800",
			                "figureInactiveBackground": "#ffd3d3d3",
			                "selectedBackground": "#ff696969",
			                "background": "#ffd7e6f7",
			                "inactiveBackground": "#ffd3d3d3",
			                "font": "맑은 고딕,11,bold",
			                "border": "#ff313539,0",
			            },
			            "footer": {
			                "borderTop": "#ffd8e3f0,1",
			                "borderRight": "#ffd8e3f0,1",
			                "borderBottom": "#ffffffff,0",
			                "borderLeft": "#ffffffff,0",
			                "paddingRight": "2",
			                "paddingTop": "2",
			                "paddingBottom": "2",
			                "paddingLeft": "2",
			                "iconAlignment": "center",
			                "iconIndex": "0",
			                "iconOffset": "0",
			                "iconLocation": "left",
			                "iconPadding": "0",
			                "contentFit": "auto",
			                "foreground": "#ff000000",
			                "hoveredMaskBackground": "#1f5292f7",
			                "selectedForeground": "#ffffffff",
			                "disabledForeground": "#ff808080",
			                "hoveredBackground": "#1f5292f7",
			                "textAlignment": "center",
			                "lineAlignment": "center",
			                "figureBackground": "#ff008800",
			                "figureInactiveBackground": "#ffd3d3d3",
			                "selectedBackground": "#ff696969",
			                "background": "#ff9cbade",
			                "inactiveBackground": "#ffd3d3d3",
			                "font": "맑은 고딕,11,bold",
			                "border": "#ffffffff,0",
			            },
			            "head": {
			                "borderTop": "#ffffffff,1",
			                "borderRight": "#ff5d8cc9,1",
			                "borderBottom": "#ff5d8cc9,1",
			                "borderLeft": "#ffffffff,1",
			                "paddingTop": "2",
			                "paddingRight": "2",
			                "paddingBottom": "2",
			                "paddingLeft": "2",
			                "iconAlignment": "center",
			                "iconIndex": "0",
			                "iconOffset": "0",
			                "iconLocation": "left",
			                "iconPadding": "0",
			                "contentFit": "auto",
			                "foreground": "#ff002f6e",
			                "hoveredMaskBackground": "linear,#fffff8a9,#ffffd75e,90",
			                "selectedForeground": "#ffff0000",
			                "disabledForeground": "#ff808080",
			                "hoveredBackground": "linear,#fffff8a9,#ffffd75e,90",
			                "textAlignment": "center",
			                "hoveredForeground": "#ff002f6e",
			                "lineAlignment": "center",
			                "figureBackground": "#ff000000",
			                "figureInactiveBackground": "#ffd3d3d3",
			                "selectedBackground": "#ffff0000",
			                "background": "linear,#ffe9f0f8,#ffc3d8f1,90",
			                "inactiveBackground": "#ffd3d3d3",
			                "font": "맑은 고딕,11,bold",
			                "border": "#ff313539,1",
			            },
			            "foot": {
			                "borderTop": "#ff79828b,1",
			                "borderRight": "#ff9099a3,1",
			                "paddingTop": "2",
			                "paddingLeft": "2",
			                "paddingBottom": "1",
			                "iconAlignment": "center",
			                "iconIndex": "0",
			                "iconOffset": "0",
			                "iconLocation": "left",
			                "iconPadding": "0",
			                "contentFit": "auto",
			                "foreground": "#ff000000",
			                "hoveredMaskBackground": "#1f5292f7",
			                "selectedForeground": "#ffffffff",
			                "disabledForeground": "#ff808080",
			                "hoveredBackground": "#1f5292f7",
			                "textAlignment": "near",
			                "lineAlignment": "center",
			                "figureBackground": "#ff008800",
			                "figureInactiveBackground": "#ffd3d3d3",
			                "selectedBackground": "#ff696969",
			                "background": "#ffdee2e7",
			                "inactiveBackground": "#ffd3d3d3",
			                "font": "맑은 고딕,12",
			                "border": "#88888888,1",
			            },
			            "headerBar": {
			                "borderTop": "#ffffffff,1",
			                "borderRight": "#ffffffff,0",
			                "borderBottom": "#ffffffff,0",
			                "borderLeft": "#ffffffff,1",
			                "paddingTop": "2",
			                "paddingRight": "2",
			                "paddingBottom": "2",
			                "paddingLeft": "2",
			                "iconAlignment": "center",
			                "iconIndex": "0",
			                "iconOffset": "0",
			                "iconLocation": "left",
			                "iconPadding": "0",
			                "contentFit": "auto",
			                "foreground": "#ff002f6e",
			                "hoveredMaskBackground": "#1f5292f7",
			                "selectedForeground": "#ffffffff",
			                "disabledForeground": "#ff808080",
			                "hoveredBackground": "#1f5292f7",
			                "textAlignment": "near",
			                "lineAlignment": "center",
			                "figureBackground": "#ff498ee1",
			                "figureInactiveBackground": "#ffd3d3d3",
			                "selectedBackground": "#ff696969",
			                "background": "#ffd7e6f7",
			                "inactiveBackground": "#ffd3d3d3",
			                "font": "맑은 고딕,11",
			                "border": "#ffffffff,0",
			            },
			            "footerBar": {
			                "borderTop": "#ffd7e6f7,1",
			                "borderRight": "#ffd7e6f7,1",
			                "borderBottom": "#ffffffff,0",
			                "paddingLeft": "2",
			                "paddingTop": "2",
			                "paddingRight": "2",
			                "paddingBottom": "2",
			                "borderLeft": "#ffffffff,0",
			                "iconAlignment": "center",
			                "iconIndex": "0",
			                "iconOffset": "0",
			                "iconLocation": "left",
			                "iconPadding": "0",
			                "contentFit": "auto",
			                "foreground": "#ff000000",
			                "hoveredMaskBackground": "#1f5292f7",
			                "selectedForeground": "#ffffffff",
			                "disabledForeground": "#ff808080",
			                "hoveredBackground": "#1f5292f7",
			                "textAlignment": "near",
			                "lineAlignment": "center",
			                "figureBackground": "#ff008800",
			                "figureInactiveBackground": "#ffd3d3d3",
			                "selectedBackground": "#ff696969",
			                "background": "#ff9cbade",
			                "inactiveBackground": "#ffd3d3d3",
			                "font": "맑은 고딕,12",
			                "border": "#ffffffff,0",
			            },
			            "bar": {
			                "borderTop": "#ffffffff,0",
			                "borderRight": "#ff85a8d0,1",
			                "borderBottom": "#ff85a8d0,0",
			                "borderLeft": "#ffffffff,1",
			                "paddingTop": "2",
			                "paddingRight": "2",
			                "paddingBottom": "2",
			                "paddingLeft": "2",
			                "iconAlignment": "center",
			                "iconIndex": "0",
			                "iconOffset": "0",
			                "iconLocation": "left",
			                "iconPadding": "0",
			                "contentFit": "auto",
			                "foreground": "#ff002f6e",
			                "hoveredMaskBackground": "#1f5292f7",
			                "selectedForeground": "#ffffffff",
			                "disabledForeground": "#ff808080",
			                "hoveredBackground": "#1f5292f7",
			                "textAlignment": "near",
			                "lineAlignment": "center",
			                "figureBackground": "#ff008800",
			                "figureInactiveBackground": "#ffd3d3d3",
			                "selectedBackground": "#ff696969",
			                "background": "#ffd7e6f7",
			                "inactiveBackground": "#ffd3d3d3",
			                "font": "맑은 고딕,11",
			                "border": "#ff313539,0",
			            },
			            "panel": {
			                "borderTop": "#ffffffff,1",
			                "borderRight": "#ff5d8cc9,1",
			                "borderBottom": "#ff5d8cc9,1",
			                "borderLeft": "#ffffffff,1",
			                "paddingTop": "1",
			                "paddingRight": "1",
			                "paddingBottom": "1",
			                "paddingLeft": "1",
			                "iconAlignment": "center",
			                "iconIndex": "0",
			                "iconOffset": "0",
			                "iconLocation": "left",
			                "iconPadding": "0",
			                "contentFit": "auto",
			                "foreground": "#ff002f6e",
			                "hoveredMaskBackground": "#fffff5a2",
			                "selectedForeground": "#ffff0000",
			                "disabledForeground": "#ff808080",
			                "hoveredBackground": "#fffff5a2",
			                "textAlignment": "center",
			                "hoveredForeground": "#ff002f6e",
			                "lineAlignment": "center",
			                "figureBackground": "#ff000000",
			                "figureInactiveBackground": "#ffd3d3d3",
			                "line": "#ff5d8cc9,1",
			                "selectedBackground": "#ffff0000",
			                "background": "#ffd7e6f7",
			                "inactiveBackground": "#ffd3d3d3",
			                "font": "돋움,11",
			                "border": "#ff5d8cc9,1",
			            }
			        },
					/*숫자 열 (첫열)*/
			        "indicator": {
						/*숫자열 테두리 속성*/
			            "borderTop": "#ffE4E4E4,1",
			            "borderRight": "#ffCDCCCC,1",
			            "borderBottom": "#ffCDCCCC,1",
			            "borderLeft": "#ffE4E4E4,1",
						/*숫자열 안쪽 간격*/
			            "paddingTop": "2",
						"paddingRight": "2",
			            "paddingBottom": "2",
			            "paddingLeft": "2",
						/*숫자열 배경 및 글자 속성*/
			            "background": "#ffE4E4E4",
			            "foreground": "#ff393939",
			            "font": "돋움,11",
						/*호버시 배경 및 글자 속성*/
			            "hoveredBackground": "#5f666666",
			            "hoveredForeground": "#ff393939",
						/*셀을 선택시 배경 및 글자 속성*/
			            "selectedBackground": "#331F9CE0",
			            "figureBackground": "#ff5E5E5E",
			            "iconAlignment": "center",
			            "iconIndex": "0",
			            "iconOffset": "0",
			            "iconLocation": "left",
			            "iconPadding": "0",
			            "contentFit": "auto",
			            "textAlignment": "center",
			            "lineAlignment": "center",
			            "hoveredMaskBackground": "#fffff0b2",
			            "selectedForeground": "#ffffffff",
			            "disabledForeground": "#ff808080",
			            "figureInactiveBackground": "#ffd3d3d3",
			            "inactiveBackground": "#ffd3d3d3",
			            "border": "#ffFF0000,1",
			            "head": {
							/*숫자열 안쪽 테두리속성*/
				            "borderTop": "#ffCDCCCC,0",
			    	        "borderRight": "#ffCDCCCC,1",
				            "borderBottom": "#ffCDCCCC,1",
			            	"borderLeft": "#ffE4E4E4,1",
							/*숫자열 안쪽 간격*/
			     	       	"paddingTop": "2",
							"paddingRight": "2",
			            	"paddingBottom": "2",
			    	        "paddingLeft": "2",
							/*숫자열 배경 및 글자 속성*/
			            	"background": "linear, #FFF2F2F2,#FFDFDFDF, 90",
				       	    "foreground": "#ff393939",
			            	"font": "돋움,11",
							/*호버시 배경 및 글자 속성*/
			            	"hoveredBackground": "#ffBEAED4",
			            	"hoveredForeground": "#ff402B5F",
							/*셀을 선택시 배경 및 글자 속성*/
			            	"figureBackground": "#ff5E5E5E",
			            	"selectedBackground": "#ffC0D2E2",
			           	 	"iconAlignment": "center",
			            	"iconIndex": "0",
			            	"iconOffset": "0",
			            	"iconLocation": "left",
			            	"iconPadding": "0",
			            	"contentFit": "auto",
			            	"textAlignment": "center",
			            	"lineAlignment": "center",
			            	"hoveredMaskBackground": "#fffff0b2",
			            	"selectedForeground": "#ffffffff",
			            	"disabledForeground": "#ff808080",
			            	"figureInactiveBackground": "#ffd3d3d3",
			            	"inactiveBackground": "#ffd3d3d3",
			            	"border": "#ffFF0000,1",
			            },
			            "foot": {
			                "borderTop": "#ff79828b,1",
			                "borderRight": "#ff9099a3,1",
			                "borderBottom": "#ff808080,1",
			                "borderLeft": "#ffffffff,1",
			                "paddingTop": "2",
			                "paddingRight": "2",
			                "paddingBottom": "2",
			                "paddingLeft": "2",
			                "iconAlignment": "center",
			                "iconIndex": "0",
			                "iconOffset": "0",
			                "iconLocation": "left",
			                "iconPadding": "0",
			                "contentFit": "auto",
			                "foreground": "#ff000000",
			                "hoveredMaskBackground": "#1f5292f7",
			                "selectedForeground": "#ffffffff",
			                "disabledForeground": "#ff808080",
			                "hoveredBackground": "#1f5292f7",
			                "textAlignment": "center",
			                "lineAlignment": "center",
			                "figureBackground": "#ff002f6e",
			                "figureInactiveBackground": "#ffd3d3d3",
			                "selectedBackground": "#ff696969",
			                "background": "#ffdee2e7",
			                "inactiveBackground": "#ffd3d3d3",
			                "font": "맑은 고딕,12",
			                "border": "#88888888,1",
			            }
			        },
					/*체크박스가 있는 열*/
			        "checkBar": {
						/*체크박스 배경 색*/
			            "background": "#ffffffff",
						/*체크박스 체크 색*/
			            "figureBackground": "#ff5f5f5f",
						/*체크박스 테두리속성*/
			            "borderRight": "#ffCDCCCC,1",
			            "borderBottom": "#ffCDCCCC,1",
						/*체크박스 간격 속성*/
			            "paddingTop": "2",
			            "paddingRight": "2",
			            "paddingBottom": "2",
			            "paddingLeft": "2",
			            "iconAlignment": "center",
			            "iconIndex": "0",
			            "iconOffset": "0",
			            "iconLocation": "left",
			            "iconPadding": "0",
			            "contentFit": "auto",
			            "foreground": "#ff555555",
			            "hoveredMaskBackground": "#1f5292f7",
			            "selectedForeground": "#ffffffff",
			            "disabledForeground": "#ff808080",
			            "hoveredBackground": "#1f5292f7",
			            "textAlignment": "center",
			            "lineAlignment": "center",
			            "figureInactiveBackground": "#ffd3d3d3",
			            "selectedBackground": "#ff696969",
			            "inactiveBackground": "#ffd3d3d3",
			            "font": "맑은 고딕,12",
			            "border": "#ff313539,1",
			            "head": {
							/*체크박스 배경색*/
				            "background": "linear, #FFF2F2F2,#FFDFDFDF, 90",
			                /*체크박스 체크 색*/
			            	"figureBackground": "#ff121212",
							/*체크박스열 테두리 속성*/
			          	  	"borderTop": "#ffCDCCCC,0",
			          	  	"borderRight": "#ffCDCCCC,1",
			          	  	"borderBottom": "#ffCDCCCC,1",
			          	  	"borderLeft": "#ffE4E4E4,1",
							/*체크박스 간격 속성*/
			                "paddingTop": "2",
			                "paddingRight": "2",
			                "paddingBottom": "2",
			                "paddingLeft": "2",
			                "iconAlignment": "center",
			                "iconIndex": "0",
			                "iconOffset": "0",
			                "iconLocation": "left",
			                "iconPadding": "0",
			                "contentFit": "auto",
			                "foreground": "#ff000000",
			                "hoveredMaskBackground": "#1f5292f7",
			                "selectedForeground": "#ffffffff",
			                "disabledForeground": "#ff808080",
			                "hoveredBackground": "#1f5292f7",
			                "textAlignment": "center",
			                "hoveredForeground": "#ffffffff",
			                "lineAlignment": "center",
			                "figureInactiveBackground": "#ffd3d3d3",
			                "selectedBackground": "#ff696969",
			                "inactiveBackground": "#ffd3d3d3",
			                "font": "맑은 고딕,12",
			                "border": "#ff000000,0",
			            },
			            "foot": {
			                "borderTop": "#ff79828b,1",
			                "borderRight": "#ff9099a3,1",
			                "borderBottom": "#ff808080,1",
			                "borderLeft": "#ffffffff,1",
			                "paddingTop": "2",
			                "paddingRight": "2",
			                "paddingBottom": "2",
			                "paddingLeft": "2",
			                "iconAlignment": "center",
			                "iconIndex": "0",
			                "iconOffset": "0",
			                "iconLocation": "left",
			                "iconPadding": "0",
			                "contentFit": "auto",
			                "foreground": "#ff000000",
			                "hoveredMaskBackground": "#1f5292f7",
			                "selectedForeground": "#ffffffff",
			                "disabledForeground": "#ff808080",
			                "hoveredBackground": "#1f5292f7",
			                "textAlignment": "center",
			                "lineAlignment": "center",
			                "figureBackground": "#ff008800",
			                "figureInactiveBackground": "#ffd3d3d3",
			                "selectedBackground": "#ff696969",
			                "background": "#ffdee2e7",
			                "inactiveBackground": "#ffd3d3d3",
			                "font": "맑은 고딕,12",
			                "border": "#88888888,1",
			            }
			        },
					/*상태 바*/	
			        "stateBar": {
			            "borderRight": "#ffCDCCCC,1",
			            "borderBottom": "#ffCDCCCC,1",
			            "paddingTop": "2",
			            "paddingRight": "2",
			            "paddingBottom": "2",
			            "paddingLeft": "2",
			            "iconAlignment": "center",
			            "iconIndex": "0",
			            "iconOffset": "0",
			            "iconLocation": "left",
			            "iconPadding": "0",
			            "contentFit": "auto",
			            "foreground": "#ff000000",
			            "hoveredMaskBackground": "#1f5292f7",
			            "selectedForeground": "#ffffffff",
			            "disabledForeground": "#ff808080",
			            "hoveredBackground": "#1f5292f7",
			            "textAlignment": "center",
			            "lineAlignment": "center",
			            "figureBackground": "#ff008800",
			            "figureInactiveBackground": "#ffd3d3d3",
			            "selectedBackground": "#ff696969",
			            "background": "#ffffffff",
			            "inactiveBackground": "#ffd3d3d3",
			            "font": "맑은 고딕,12",
			            "border": "#ff313539,1",
			            "head": {
							/*상태 배경색*/
				            "background": "#ffE4E4E4",
			                /*상태 체크 색*/
			            	"figureBackground": "#ff008EDC",
							/*상태 테두리 속성*/
			          	  	"borderTop": "#ffCDCCCC,1",
			          	  	"borderRight": "#ffCDCCCC,1",
			          	  	"borderBottom": "#ffCDCCCC,1",
			          	  	"borderLeft": "#ffE4E4E4,1",
							/*상태 간격 속성*/
			                "paddingTop": "2",
			                "paddingRight": "2",
			                "paddingBottom": "2",
			                "paddingLeft": "2",
			                "iconAlignment": "center",
			                "iconIndex": "0",
			                "iconOffset": "0",
			                "iconLocation": "left",
			                "iconPadding": "0",
			                "contentFit": "auto",
			                "foreground": "#ff000000",
			                "hoveredMaskBackground": "#1f5292f7",
			                "selectedForeground": "#ffffffff",
			                "disabledForeground": "#ff808080",
			                "hoveredBackground": "#1f5292f7",
			                "textAlignment": "center",
			                "hoveredForeground": "#ffffffff",
			                "lineAlignment": "center",
			                "figureBackground": "#ff008800",
			                "figureInactiveBackground": "#ffd3d3d3",
			                "selectedBackground": "#ff696969",
			                "inactiveBackground": "#ffd3d3d3",
			                "font": "맑은 고딕,12",
			                "border": "#ff000000,0",
			            },
			            "foot": {
			                "borderTop": "#ff79828b,1",
			                "borderRight": "#ff9099a3,1",
			                "borderBottom": "#ff808080,1",
			                "borderLeft": "#ffffffff,1",
			                "paddingTop": "2",
			                "paddingRight": "2",
			                "paddingBottom": "2",
			                "paddingLeft": "2",
			                "iconAlignment": "center",
			                "iconIndex": "0",
			                "iconOffset": "0",
			                "iconLocation": "left",
			                "iconPadding": "0",
			                "contentFit": "auto",
			                "foreground": "#ff000000",
			                "hoveredMaskBackground": "#1f5292f7",
			                "selectedForeground": "#ffffffff",
			                "disabledForeground": "#ff808080",
			                "hoveredBackground": "#1f5292f7",
			                "textAlignment": "center",
			                "lineAlignment": "center",
			                "figureBackground": "#ff008800",
			                "figureInactiveBackground": "#ffd3d3d3",
			                "selectedBackground": "#ff696969",
			                "background": "#ffdee2e7",
			                "inactiveBackground": "#ffd3d3d3",
			                "font": "맑은 고딕,12",
			                "border": "#88888888,1",
			            }
			        },
			        "selection": {
			            "paddingTop": "0",
			            "paddingRight": "0",
			            "paddingBottom": "0",
			            "paddingLeft": "0",
			            "iconAlignment": "center",
			            "iconIndex": "0",
			            "iconOffset": "0",
			            "iconLocation": "left",
			            "iconPadding": "0",
			            "contentFit": "auto",
			            "foreground": "#ff000000",
			            "hoveredMaskBackground": "#1f5292f7",
			            
			            "disabledForeground": "#ff808080",
			            "hoveredBackground": "#1f5292f7",
			            "textAlignment": "center",
			            "lineAlignment": "center",
			            "figureBackground": "#ff008800",
			            "figureInactiveBackground": "#ffd3d3d3",
			
			/* changed*/
						"selectedForeground": "#ffffffff",            
						"selectedBackground": "#ff6498aa",
						
			/*  selected row color */
			            "background": "#00ffffff",
			            "inactiveBackground": "#FFd3d3d3",
			            "font": ",13",
			            "border": "#FF6599ea,2",
			        }
    };